4.Sistema/tradebitcoin/config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users
  resources :clients
  resources :users

  get 'sobre' => 'index#sobre', as: :sobre

  get 'ajuda' => 'index#ajuda', as: :ajuda

  get 'contato' => 'index#contato', as: :contato

  root "index#index"
end

4.Sistema/tradebitcoin/app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :client
end

4.Sistema/tradebitcoin/app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
end

4.Sistema/tradebitcoin/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :client
  accepts_nested_attributes_for :client
end

4.Sistema/tradebitcoin/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.client_id = current_user.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Conta criada com sucesso.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Conta atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Conta removida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:active, :saldo, :data_encerramento, :client_id)
    end
end

4.Sistema/tradebitcoin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

4.Sistema/tradebitcoin/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:senha, :verificado, :user_id)
    end
end

4.Sistema/tradebitcoin/app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end

  def sobre
  end

  def ajuda
  end

  def contato
  end
  
end

4.Sistema/tradebitcoin/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    if Account.find_by_client_id(current_user.id)
      @contas = Account.find_by_client_id(current_user.id).id
    else
      @contas = false
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    puts @user
  end

  # GET /users/new
  def new
    @user = User.new
    @client = Client.new
    @user.client = @client
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    r = @user.build_client
    login = params["user"]["client"]["login"]
    senha = params["user"]["client"]["senha"]

    r.login = login
    r.senha = senha

    puts @user
    # c = Client.new
    # c.user = @user
    #
    # debugger
    #
    # c.login = params[:user][:client][:login]
    # c.save

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário criado com sucesso!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuário atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário removido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :rg, :cpf, client_attributes: [:id, :login, :senha])
    end
end

4.Sistema/tradebitcoin/app/helpers/accounts_helper.rb
module AccountsHelper
end

4.Sistema/tradebitcoin/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def minhas_contas
    #id = current_user.id
  end
end

4.Sistema/tradebitcoin/app/helpers/clients_helper.rb
module ClientsHelper
end

4.Sistema/tradebitcoin/app/helpers/index_helper.rb
module IndexHelper
end

4.Sistema/tradebitcoin/app/helpers/users_helper.rb
module UsersHelper
end

4.Sistema/tradebitcoin/app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Ativar?<br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :saldo %><br>
    <%= f.text_field :saldo %>
  </div>
  <div class="field">
    Encerrar em alguma data?<br>
    <%= f.datetime_select :data_encerramento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4.Sistema/tradebitcoin/app/views/accounts/edit.html.erb
<h1>Edite sua conta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', @account %>

4.Sistema/tradebitcoin/app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Minhas contas</h1>

<table>
  <thead>
    <tr>
      <th>Ativa?</th>
      <th>Saldo (R$)</th>
      <th>Data encerramento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.active %></td>
        <td><%= account.saldo %></td>
        <td><%= account.data_encerramento %></td>
        <td><%= link_to 'Ver detalhes', account %></td>
        <td><%= link_to 'Gerenciar', edit_account_path(account) %></td>
        <td><%= link_to 'remover', account, method: :delete, data: { confirm: 'Remover sua conta?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

4.Sistema/tradebitcoin/app/views/accounts/new.html.erb
<h1>Minha conta</h1>

<%= render 'form' %>

<%#= link_to 'Back', accounts_path %>

4.Sistema/tradebitcoin/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conta ativa?</strong>
  <%= (@account.active) ? 'Sim': 'Não' %>
</p>

<p>
  <strong>Saldo: R$</strong>
  <%= @account.saldo %>
</p>

<p>
  <strong>Data encerramento:</strong>
  <%= @account.data_encerramento %>
</p>

<%= link_to 'Editar', edit_account_path(@account) %> 

4.Sistema/tradebitcoin/app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <h3>
    Usuário: <%= @client.user.name %>
  </h3>

  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>

  <div class="field">
    <%= f.label :verificado %><br>
    <%= f.check_box :verificado %>
  </div>


  <div class="field">
    <!--< %= f.label :user_id %><br>-->
    <!--< %= f.text_field :user_id %>-->
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4.Sistema/tradebitcoin/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

4.Sistema/tradebitcoin/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Senha</th>
      <th>Verificado</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.login %></td>
        <td><%= client.senha %></td>
        <td><%= client.verificado %></td>
        <% if client.user %>
          <td><%= client.user.name %></td>
        <% end %>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

4.Sistema/tradebitcoin/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

4.Sistema/tradebitcoin/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Senha:</strong>
  <%= @client.senha %>
</p>

<p>
  <strong>Verificado:</strong>
  <%= @client.verificado %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

4.Sistema/tradebitcoin/app/views/index/_footer.html.erb
<div class="col-md-12 footer">
  <center>
    <p class="col-md-6 center text-center">
      <%= link_to 'Home', '/' %> |
      <%= link_to 'Sobre o Sistema', :sobre %> |
      <%= link_to 'Ajuda', :ajuda %> |
      <%= link_to 'Contato', :contato %>
    </p>
    <p>
      TradeBitcoin SI UFG <%= Time.now.year %> © Todos os direitos reservados
    </p>
  </center>
</div>

4.Sistema/tradebitcoin/app/views/index/ajuda.html.erb
Ainda inseguro?

<p> Converse com quem já está na Tradebitcoin!!</p>

<p> <%= link_to 'Comunidade no Facebook', 'http://facebook.com' %></p>

<p> <%= link_to 'Grupo no Telegram', 'http://web.telegram.org' %></p>

4.Sistema/tradebitcoin/app/views/index/contato.html.erb
<p>
    Fornecemos suporte online 24h por dia, 7 dias por semana.
    <br><br>
    Entre em contato com <strong>suporte@tradebitcoinsi.ufg.br</strong> e tire suas dúvidas.
    <br>
    <h4>ou ligue (xx) 9992-9999<h4>
    <h5>atendimento das 7h00 as 19h00<h5>
</p>

4.Sistema/tradebitcoin/app/views/index/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trade Bitcoin</title>
</head>
<body>

<div class="tradebitcoin container">
    <div class="col-md-12 text-center main">
      <h3>BitCoinTrader</h3>

        <p>Compre e venda bitcoins na maior corretora do Brasil!!</p>

      <div class="col-md-12">

        <div class="col-md-6 login-box">

        <%- if user_signed_in? %>
            <div class="welcome"> Bem vindo, <strong><%= current_user.email %></strong> </div>

            <%= link_to 'Veja seu perfil', "users/#{current_user.id}" %>

            <br>

            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
            
        <%- else %>
            <p>Para começar, faça seu <%= link_to 'login', user_session_path %></p>
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="field">
                  E-mail<br />
                  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                </div>
    
                <div class="field">
                  Senha<br />
                  <%= f.password_field :password, autocomplete: "off" %>
                </div>
    
                <% if devise_mapping.rememberable? -%>
                  <div class="field">
                    <%= f.check_box :remember_me %>
                    Lembrar-se de mim
                  </div>
                <% end -%>
    
                <div class="actions">
                  <%= f.submit "Entrar" %>
                </div>
              <% end %>
    
              <%= render "devise/shared/links" %>
        <% end -%>

        </div>

      </div>

    </div>

</div>

</body>
</html>

4.Sistema/tradebitcoin/app/views/index/sobre.html.erb
A <strong>TradeBitcoin</strong> é uma nova empresa revolucionária na compra e venda de bitcoins.
<br><br>
Basta <%= link_to 'criar sua conta', '/users/sign_up' %> e começar a operar diretamente na blockchain!!

4.Sistema/tradebitcoin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradebitcoin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main-template-tradebitcoin">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <p>
    <%= image_tag "bitcoin.jpg" %>
  </p>

  <%= yield %>

  <%= render 'index/footer' %>

</div>


</body>
</html>

4.Sistema/tradebitcoin/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :rg %><br>
    <%= f.number_field :rg %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.number_field :cpf %>
  </div>

  <%= f.fields_for @user.build_client do |c| %>
    <div class="field">
      <%= c.label :login %><br>
      <%= c.text_field :login %>
    </div>

    <div class="field">
      <%= c.label :senha %><br>
      <%= c.text_field :senha %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

4.Sistema/tradebitcoin/app/views/users/edit.html.erb
<h1>Edite seu perfil</h1>

<%= render 'form' %>

<%= link_to 'Ver perfil', @user %> 
<%= link_to 'meus dados', users_path %>

4.Sistema/tradebitcoin/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meus dados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>E-mail</th>
      <th>RG</th>
      <th>CPF</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if current_user && (user.id == current_user.id) %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.rg %></td>
          <td><%= user.cpf %></td>
          <td><%= link_to 'Ver', user %></td>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
          <td><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Confirma remoção deste usuário?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<% if @contas %>
  <%= link_to 'ver minha conta', "/accounts/#{@contas}" %>
<% else %>
  <%= link_to 'Criar carteira de bitcoin', new_account_path %>
<% end %>

4.Sistema/tradebitcoin/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

4.Sistema/tradebitcoin/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>


<% if @user.client %>
  <p>
    <strong>login:</strong>
    <%= @user.client.login %>
  </p>

  <p>
    <strong>senha:</strong>
    <%= @user.client.senha %>
  </p>

<% end %>

<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>RG:</strong>
  <%= @user.rg %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @user.cpf %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %>
<%#= link_to 'voltar', users_path %>